
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gnz.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POR = 22;
  public static final int CHAR = 9;
  public static final int CORCHETE_CERRADO = 38;
  public static final int ELSIF = 40;
  public static final int DOUBLE = 15;
  public static final int DOS_PUNTOS = 45;
  public static final int NUMERO_DECIMALF = 18;
  public static final int PORCENTAJE = 25;
  public static final int INT = 12;
  public static final int PRINTLN = 48;
  public static final int ARRAY = 46;
  public static final int DECLARACION_STRING = 20;
  public static final int SEPARADOR = 54;
  public static final int PARENTESIS_ABIERTO = 35;
  public static final int FOR = 44;
  public static final int IDENTIFICADOR = 5;
  public static final int NOT = 32;
  public static final int AND = 33;
  public static final int DECLARACION_CARACTER = 10;
  public static final int OR = 34;
  public static final int DIV = 24;
  public static final int MAIN = 53;
  public static final int IF = 39;
  public static final int CORCHETE_ABIERTO = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 52;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int COMA = 4;
  public static final int MENOS = 23;
  public static final int MENOR = 26;
  public static final int VOID = 51;
  public static final int PCOMA = 2;
  public static final int ASIGNACION = 3;
  public static final int BYTE = 11;
  public static final int MAYOR = 27;
  public static final int NUMERO_DECIMAL = 17;
  public static final int ELSE = 41;
  public static final int DISTINTO_DE = 30;
  public static final int WHILE = 42;
  public static final int IGUAL_A = 31;
  public static final int MAYOR_IGUAL = 29;
  public static final int FLOAT = 14;
  public static final int LONG = 13;
  public static final int PARENTESIS_CERRADO = 36;
  public static final int STRING = 19;
  public static final int MENOR_IGUAL = 28;
  public static final int FALSE = 8;
  public static final int SCANS = 49;
  public static final int NUMERO_ENTERO = 16;
  public static final int PRINT = 47;
  public static final int DO = 43;
  public static final int SCANN = 50;
  public static final int MAS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PCOMA",
  "ASIGNACION",
  "COMA",
  "IDENTIFICADOR",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "CHAR",
  "DECLARACION_CARACTER",
  "BYTE",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "NUMERO_ENTERO",
  "NUMERO_DECIMAL",
  "NUMERO_DECIMALF",
  "STRING",
  "DECLARACION_STRING",
  "MAS",
  "POR",
  "MENOS",
  "DIV",
  "PORCENTAJE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "DISTINTO_DE",
  "IGUAL_A",
  "NOT",
  "AND",
  "OR",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "IF",
  "ELSIF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "DOS_PUNTOS",
  "ARRAY",
  "PRINT",
  "PRINTLN",
  "SCANS",
  "SCANN",
  "VOID",
  "RETURN",
  "MAIN",
  "SEPARADOR"
  };
}

